[project]
name = "ad-hoc-requests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.5",
    "dotenv>=0.9.9",
    "fastexcel>=0.19.0",
    "fsspec>=2026.3.0",
    "plotly[express]>=6.7.0",
    "polars>=1.39.3",
    "requests>=2.33.1",
]

[project.scripts]
ad-hoc-requests = "ad_hoc_requests:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "kaleido>=1.2.0",
    "nbformat>=5.10.4",
    "ty>=0.0.31",
]
